"""add_shortlink_updated_at

Revision ID: 00d94a6bb187
Revises: 5e1a6a53d895
Create Date: 2026-06-26 09:02:16.168917
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '00d94a6bb187'
down_revision = '5e1a6a53d895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shortlink_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shortlink_updated_at')
    # ### end Alembic commands ###
