"""add_product_tags_and_file_fields

Revision ID: 07cd2fc205f7
Revises: 70286db064c5
Create Date: 2026-06-25 16:02:29.164195
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '07cd2fc205f7'
down_revision = '70286db064c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('main_file_url', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('license_type', sa.String(length=50), server_default=sa.text("'personal'"), nullable=False))
    op.add_column('products', sa.Column('user_tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('products', sa.Column('ai_tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('products', sa.Column('software_tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('products', sa.Column('format_tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'format_tags')
    op.drop_column('products', 'software_tags')
    op.drop_column('products', 'ai_tags')
    op.drop_column('products', 'user_tags')
    op.drop_column('products', 'license_type')
    op.drop_column('products', 'main_file_url')
    # ### end Alembic commands ###
