"""add_profile_fields_to_users

Revision ID: 70286db064c5
Revises: c7fdceef47c2
Create Date: 2026-06-25 15:37:14.933027
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '70286db064c5'
down_revision = 'c7fdceef47c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('users', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_links')
    op.drop_column('users', 'specialties')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'banner_url')
    # ### end Alembic commands ###
