"""update withdrawal

Revision ID: c69eecacc997
Revises: ab378f7aa622
Create Date: 2026-06-28 15:23:10.739337
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c69eecacc997'
down_revision = 'ab378f7aa622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
