"""add verification fields to users

Revision ID: c7fdceef47c2
Revises: 0001_initial_schema
Create Date: 2026-06-24 21:11:15.039541
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c7fdceef47c2'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_otp_expires_at')
    op.drop_column('users', 'verification_otp')
    # ### end Alembic commands ###
