"""add shortlink and is_gold to users

Revision ID: dd81cb8657a0
Revises: ead95d96ab21
Create Date: 2026-06-25 16:42:27.440946
"""
import secrets
import string

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'dd81cb8657a0'
down_revision = 'ead95d96ab21'
branch_labels = None
depends_on = None


_ALPHABET = string.ascii_lowercase + string.digits


def _random_shortlink(length: int = 10) -> str:
    return ''.join(secrets.choice(_ALPHABET) for _ in range(length))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_gold', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('shortlink', sa.String(length=32), nullable=True))

    # Populate unique shortlinks for every existing user
    conn = op.get_bind()
    users = conn.execute(sa.text("SELECT id FROM users")).fetchall()
    existing: set[str] = set()
    for (uid,) in users:
        sl = _random_shortlink()
        while sl in existing:
            sl = _random_shortlink()
        existing.add(sl)
        conn.execute(sa.text("UPDATE users SET shortlink = :sl WHERE id = :uid"), {"sl": sl, "uid": str(uid)})

    op.create_index('ix_users_shortlink', 'users', ['shortlink'], unique=True)
    op.create_unique_constraint(None, 'users', ['shortlink'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_shortlink', table_name='users')
    op.drop_column('users', 'shortlink')
    op.drop_column('users', 'is_gold')
    # ### end Alembic commands ###
