import * as XLSX from "xlsx";

export interface Order {
  id: string;
  status: string;
  totalAmount: number;
  createdAt: string;
  buyer: { id: string; username: string; email: string };
}

export interface OrdersData {
  adminOrders: {
    items: Order[];
    totalItems: number;
    totalPages: number;
  };
}

export interface ExportOptions {
  orders: Order[];
  statusFilter: string;
  generatedBy: string;
}

export const STATUS_FILTERS = [
  { label: "Tất cả", value: "" },
  { label: "Chờ xử lý", value: "pending" },
  { label: "Đang xử lý", value: "processing" },
  { label: "Hoàn thành", value: "completed" },
  { label: "Đã hủy", value: "cancelled" },
];

export const STATUS_LABELS: Record<string, string> = {
  pending: "Chờ xử lý",
  processing: "Đang xử lý",
  completed: "Hoàn thành",
  cancelled: "Đã hủy",
};

export const STATUS_BADGE_MAP: Record<string, "warning" | "info" | "success" | "danger" | "default"> = {
  pending: "warning",
  processing: "info",
  completed: "success",
  cancelled: "danger",
};

export function maskName(name: string): string {
  if (!name || name.length <= 2) return name;
  const parts = name.trim().split(" ");
  if (parts.length === 1) {
    return parts[0][0] + "***";
  }
  const firstName = parts[parts.length - 1];
  const masked = firstName[0] + "*".repeat(Math.min(firstName.length - 1, 3));
  return `${parts[0]} ${masked}`;
}

export function maskEmail(email: string): string {
  const [local, domain] = email.split("@");
  if (!local || !domain) return email;
  const visible = local.slice(0, 2);
  return `${visible}***@${domain}`;
}

export function exportToExcel({ orders, statusFilter, generatedBy }: ExportOptions) {
  const wb = XLSX.utils.book_new();

  const totalRevenue = orders
    .filter((o) => o.status === "completed")
    .reduce((sum, o) => sum + o.totalAmount, 0);

  const statusFilterLabel = statusFilter ? STATUS_LABELS[statusFilter] : "All";

  //Sheet 1: Tong quan cac giao dich => co the hien thi theo tung filter giao dich ma Admin chon
  const summaryData = [
    ["ORDER REPORT"],
    [],
    ["Generated At", new Date().toLocaleString("vi-VN")],
    ["Generated By", generatedBy],
    ["Status Filter", statusFilterLabel],
    [],
    ["Total Orders", orders.length],
    ["Total Revenue (VNĐ)", totalRevenue],
    [],
    ["─────────────────────────", "─────────────"],
    ["Order Statistics", ""],
    ["─────────────────────────", "─────────────"],
    ["Completed", orders.filter((o) => o.status === "completed").length],
    ["Pending", orders.filter((o) => o.status === "pending").length],
    ["Processing", orders.filter((o) => o.status === "processing").length],
    ["Cancelled", orders.filter((o) => o.status === "cancelled").length],
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  wsSummary["!cols"] = [{ wch: 28 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Overview");

  //Sheet 2: Chi tiet cac giao dich
  const detailRows = orders.map((order, idx) => ({
    "STT": idx + 1,
    "Order ID": order.id.slice(0, 8).toUpperCase(),
    "Customer": maskName(order.buyer.username),
    "Email": maskEmail(order.buyer.email),
    "Status": STATUS_LABELS[order.status] ?? order.status,
    "Amount (VNĐ)": order.totalAmount,
    "Created At": new Date(order.createdAt).toLocaleDateString("vi-VN"),
  }));

  const wsDetail = XLSX.utils.json_to_sheet(detailRows);
  wsDetail["!cols"] = [
    { wch: 6 },
    { wch: 14 },
    { wch: 22 },
    { wch: 26 },
    { wch: 16 },
    { wch: 18 },
    { wch: 16 },
  ];
  XLSX.utils.book_append_sheet(wb, wsDetail, "Order Details");

  const fileName = `lumine-order-report-${new Date().toISOString().slice(0, 10)}.xlsx`;
  XLSX.writeFile(wb, fileName);
}